---
- name: Criar Interface de VPN no Panorama
  hosts: all
  connection: local
  gather_facts: false

  tasks:
    - name: Criar Tunnel Interface
      paloaltonetworks.panos.panos_tunnel:
        provider:
          ip_address: "{{ ansible_host }}"
          username: "{{ ansible_user }}"
          password: "{{ ansible_password }}"
        if_name: "{{ vpn_interface_name }}"  # Ex: tunnel.10
        ip_address: "{{ vpn_tunnel_ip }}"    # Ex: 10.0.0.1/30
        description: "VPN criada via Ansible AAP"
        template: "{{ panorama_template }}"  # O Template onde a VPN vai morar
        state: 'present'
      register: tunnel_result

    - name: Resultado da Criação
      ansible.builtin.debug:
        msg: "Interface {{ vpn_interface_name }} criada no Template {{ panorama_template }}"