---
- name: Criar Interface de VPN no Panorama
  hosts: all
  connection: local
  gather_facts: false


  vars:
    device:
       ip_address: "{{ ansible_host }}"
       username: "{{ ansible_user }}"
       password: "{{ ansible_password }}"  
  
  tasks:
    - name: Criar Zona para o Peer Remoto
      paloaltonetworks.panos.panos_zone:
        zone: '{{ vpn_zone_name }}'
        mode: 'layer3'
    
    - name: Criar Tunnel Interface
      paloaltonetworks.panos.panos_tunnel:
        if_name: "{{ vpn_interface_name }}"  # Ex: tunnel.10
        ip: "{{ vpn_tunnel_ip }}"    # Ex: 10.0.0.1/30
        template: "{{ panorama_template }}"  # O Template onde a VPN vai morar
        state: 'present'
      register: tunnel_result

    - name: Resultado da Criação
      ansible.builtin.debug:
        msg: "Interface {{ vpn_interface_name }} criada no Template {{ panorama_template }}"