---
- name: Gather system info
  hosts: 192.168.0.240
  connection: local
  gather_facts: false
  
  tasks:
    - name: Gather facts for device
      paloaltonetworks.panos.panos_facts:
        provider:
          ip_address: "{{ ansible_host }}"
          username: "{{ ansible_user }}"
          password: "{{ ansible_password }}"
      register: device_facts