---
- name: Gather system info
  hosts: all
  connection: local
  gather_facts: false
  
  vars:
    ansible_python_interpreter: /home/user/Test/.venvTest/bin/python3.12

  tasks:
    - name: Gather facts for device
      paloaltonetworks.panos.panos_facts:
        provider:
          ip_address: "{{ ansible_host }}"
          username: "{{ ansible_user }}"
          password: "{{ ansible_password }}"
      register: device_facts