---
- name: Gather system info
  hosts: 192.168.0.240
  connection: local
  gather_facts: false
  
  tasks:
    - name: Gather facts for device
      paloaltonetworks.panos.panos_facts:
        provider:
          ip_address: "{{ ansible_host }}"
          username: "{{ ansible_user }}"
          password: "{{ ansible_password }}"
          port: 443
      register: device_facts  # Os dados entram aqui!

    - name: Display information
      ansible.builtin.debug:
        msg:
          # Note que agora usamos 'device_facts.ansible_facts'
          - "Hostname: {{ device_facts.ansible_facts.net_hostname | default('N/A') }}"
          - "Serial: {{ device_facts.ansible_facts.net_serial | default('N/A') }}"
          - "Model: {{ device_facts.ansible_facts.net_model | default('N/A') }}"
          - "Version: {{ device_facts.ansible_facts.net_version | default('N/A') }}"